### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by charleswong739** [ashenafee/STG#15]
# Goal

Create home screen.

# Solution

Donation Centres should be rendered using a "database" JSON listing individual centres, completion goals. This will be used as the backend for future pages (e.g. map view, etc.)

# Tasks
- [x] Rehaul bottom tab navigation
- [x] Create Donation Centre card
- [x] Create general layout
- [x] Finish Donation Centre tabs and scroll view
